### ISSUE TITLE
{"errcode":310000,"errmsg":"sign not match"}

### ISSUE THREAD

**Issue by busyhe** [x-cold/dingtalk-robot#7]

**Comment by huangang** [comment]
@BusyHe 有没有例子提供看看

**Comment by busyhe** [comment]
这是我的错误，sign最后encode加密是不需要的。

**Comment by zy0525** [comment]
> 这是我的错误，sign最后encode加密是不需要的。

https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq   文档没有及时更新
